# Site settings
title: "Generic title"
description: > 
    Desc

author: Peter-Bence Kompasz
email: pbkompasz@gmail.com  
#twitter_username: _HairForceOne
github_username: pbkompasz

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pbkompasz.me" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/ 

